port: 80
version: "1.3.0"
site_name: "Deno-Play'A"
site_logo: "https://picsum.photos/256/256"
media_root: "/media"
auth: false
auth_by_code: false
actors: false
categories: false
categories_groups: false
studios: false
scripts: false
masks: false
analytics: false
theme: 1
supported_extensions:
  - .mp4
  - .mkv
