port: 4236
playa_client_version: "1.3.0"
media_root: "/media"
supported_extensions:
  - .mp4
  - .mkv
playa_config:
  site_name: "Deno-Play'A"
  site_logo: "https://picsum.photos/256/256"
  auth: false
  auth_by_code: false
  actors: false
  categories: false
  categories_groups: false
  studios: false
  scripts: false
  masks: false
  analytics: false
  theme: 1
